追加テーブルへデータを保存する処理の実装#13
Aya0810/lamp_practice pull request #14
Opened 2021-04-29 03:31 UTC by Aya0810

保存処理を追記したので、マージ処理をよろしくお願いします。

2021-04-29 11:00 UTC, primestyleus requested changes
@Aya0810
基本の形としてはOKですが、トランザクションについて、もう少し調整の必要があります。
例えば、insert_detailの中のSQL文を、（余計なカンマを入れるなどして）あえてエラーが出る形に変えてみてください。そうするとエラーメッセージ自体は出ると思いますが、その時historiesテーブルにも保存されていない状態となるのが正しいです。「エラーが発生したかどうか」を条件にcommit/rollbackのどちらを実行するか条件分岐するとうまくいきます。

また、エラーが発生した場合は購入完了画面いはいかずにcart画面に戻ってくるのが正しい動きとなります。

もう少しだと思いますので頑張ってください。

2021-04-29 13:55 UTC, Aya0810 commented
@primestyleus 
考え方としては下記で合っているのでしょうか？
if (??? === false) {
// ロールバック
    $db->rollback();
    return false;
  }
  // コミット処理
  $db->commit();
  return true;
}

2021-04-29 14:27 UTC, primestyleus commented
@Aya0810 
はい、あってます!!

2021-05-05 13:49 UTC, primestyleus approved these changes
@Aya0810 
こちらで一旦okとしますね。もう少しシンプルな実装方法もあるので、レッスンのときに説明させてください。

2021-05-05 13:49 UTC, merged